# packages.toml
[apt]
packages = [
    "bat",
    "btop",
    "cowsay",
    "culmus",
    "distrobox",
    "fd-find",
    "git",
    "htop",
    "hunspell",
    "hunspell-he",
    "markdown",
    "miller",
    "nala",
    "pandoc",
    "podman",
    "xclip",
    "xsel",
    "copyq",
    "feh",
    "foliate",
    "easyeffects",
    "inkscape",
    "inkscape-open-symbols",
    "inkscape-textext",
    "jq",
    "kdeconnect",
    "klayout",
    "konsole",
    "krita",
    "lyx",
    "meld",
    "mpv",
    "nextcloud-desktop",
    "qalc",
    "qalculate-gtk",
    "q4wine",
    "qt5ct",
    "remmina",
    "remmina-plugin-rdp",
    "remmina-plugin-vnc",
    "ripgrep",    
    "stow",
    "texstudio",
    "tree",
    "ttf-mscorefonts-installer",
    "timeshift",
    "virt-manager",
    "vlc",
    "vokoscreen-ng",
    "xournalpp",
    "zathura",
    "zathura-djvu",
    "zathura-pdf-poppler",
    "zathura-ps",
    "zim",
    "zim-tools"
]

[flatpak]
packages = [
    "com.bitwarden.desktop",
    "com.github.flxzt.rnote",
    "com.zettlr.Zettlr",
    "io.freetubeapp.FreeTube",
    "io.github.ungoogled_software.ungoogled_chromium",
    "io.github.voxelcubes.hand-tex",
    "io.gitlab.librewolf-community",
    "org.cryptomator.Cryptomator",
    "org.gimp.GIMP",
    "org.jabref.jabref",
    "org.kde.falkon",
    "org.rncbc.qpwgraph"
]

[homebrew]
packages = [
    "atuin",
    "bat",
    "carapace",
    "difftastic",
    "dust",
    "eza",
    "fzf",
    "fd",
    "git-delta",
    "glow",
    "helix",
    "just",
    "lazygit",
    "markdown-oxide",
    "navi",
    "nushell",
    "procs",
    "sd",
    "ripgrep",
    "syncthing",
    "texlab",
    "tidy-viewer",
    "tinymist",
    "typst",
    "typstyle",
    "xsv",
    "yazi",
    "zellij",
    "zoxide"
]

[uv]
packages = [
    "basedpyright",
    "csvkit",
    "gds3xtrude",
    "ipython",
    "jupyterlab",
    "jupytext",
    "ptpython",
    "rich-cli",
    "ruff",
    "tldr",
    "trash-cli"
]
